project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: Abbildung
  tbl-prefix: Tabelle
  fig-title: Abbildung    
  tbl-title: Tabelle 
  title-delim: —     # (default is ":")

book:
  title: "Skript Bioinformatik"
  subtitle: "Der zu kurze Leitfaden"
  author: "Prof. Dr. Jochen Kruppa"
  date: "19. August 2023"
  cover-image: cover.png
  chapters:
    - index.qmd
    - literature.qmd
    - preface.qmd
    - part: quali-genet-preface.qmd
      chapters:
      - quali-genet-basic.qmd
    - part: quant-genet-preface.qmd
      chapters:
      - quant-genet-basic.qmd
    - part: data-genet-preface.qmd
      chapters: 
      - data-genet-basic.qmd
#      - matrix-basic.qmd
#    - part: functions-preface.qmd
#      chapters: 
#      - functions-basic.qmd
#      - functions-extrem-stamm.qmd
#    - part: probability-preface.qmd
#      chapters:
#      - probability-basic.qmd
#      - probability-distribution.qmd

bibliography: references.bib
lang: de 

format:
  html:
    theme: cosmo
    mermaid:
      theme: default
#  pdf:
#    documentclass: scrreprt


